### ISSUE TITLE
Is a Link always a CID?

### ISSUE THREAD

**Issue by hannahhoward** [ipld/specs#145]
The go-ipld-prime package introduces the concept of an IPLD Link concept, which currently only has one implementation, which is a CID based link. The original purpose is was simply to limit the dependencies of go-ipld-prime so it did not include go-cid and all it's dependencies.

However, this begs the question: is a Link in IPLD always a CID?

This has come up a few times in other discussions: 
https://github.com/ipld/specs/pull/117#discussion_r279998492

The current data model doc seems pretty clear: https://github.com/ipld/specs/blob/master/data-model-layer/data-model.md#link-kind

It seems like it's worth an explicit conversation and a decision.

@Stebalien @warpfork

**Comment by rvagg** [comment]
One option being discussed is the possibility of an advanced layout / composite for links whereby you encounter a thing that says it's a link but invokes some special logic to give you a CID. One version of this might be mutable links which are objects containing a CID and a location to fetch an updated CID if one exists. When you encounter this thing, it looks like a Link as far as the interface might be concerned but there's logic under the hood that is invoked transparently to turn it into a CID. I think the reason "Link" is left not being CID is that we want the flexibility to move beyond the bounds of what CID provides now. Fat pointers might be another thing that fits in this same category.

But right now, I don't believe anything else exists that might be called a "Link" other than a CID so it's a safe assumption now at least.

**Comment by warpfork** [comment]
I wouldn't worry about this too much.  The current data model doc is clear.  The code matches.

It's true that the indirection in go-ipld-prime exists so that if someone wants to use the library with plain, linkless JSON, it's possible to do so without a transitive dependence on the go-cid library and its behemoth of further transitive dependencies.  If there was a proposal to use that interface for anything else, **then** I'd consider a conversation prompted.

> But right now, I don't believe anything else exists that might be called a "Link" other than a CID so it's a safe assumption now at least.

+1

If there are any ideas about adding additional concepts of linking, we should take them through some series of exploration reports, then proposals, etc.  And while that may happen... Until then, ISTM we should treat the answer is simple: No, there are no other concepts of linking.  We implement links as a CID.  Docs talk about "linking" conceptually because that's what things do, and because that's what IP**L**D is named for, but the implementation is always CID.

**Comment by hannahhoward** [comment]
closing as not relevant for now.

**Comment by Stebalien** [comment]
Note: A link _should_ be a CID plus a path (see https://github.com/ipld/specs/issues/83, https://github.com/ipld/specs/pull/146/files#diff-c989be102856fc7df91ef19f04516e27R23). We just haven't gotten around to this yet and it's getting harder every day :(.

**Comment by warpfork** [comment]
FWiW, I don't think it's actually getting *harder*.  We're just... not putting one of our very limited handful of priority tokens on it right now, because half-assing it isn't a good idea either.  But (at least from my PoV, in the Go libraries), it's standing still, not getting harder.  And that seems optimistically fine to me.
