### ISSUE TITLE
IPLD v2: Laying out Future plans

### ISSUE THREAD

**Issue by RichardLitt** [ipld/specs#23]
I think it would be great if we could have a place to discuss future plans for IPLD. I propose we use this issue.

Specifically, I have seen transformations, programmable data & light verifiable proofs mentioned.

For example:
- What are or could be important about proof-of-membership, proof-of-non-membership, proof-of-consistency?
- How could we use transformations to do sharding, or computing on IPLD objects?
- What other communities should we look at, to emulate going forward? (Such as distributed systems community mentioned, ie. Chord and Spark).

If there is a better way to phrase this issue, I am all-ears. Might be good to split it up into a few issues.

**Comment by rvagg** [comment]
Closing due to staleness as per team agreement to clean up the issue tracker a bit (https://github.com/ipld/team-mgmt/pull/28). This doesn't mean this issue is off the table entirely, it's just not on the current active stack but may be revisited in the near future. If you feel there is something pertinent here, please speak up, reopen, or open a new issue. [/boilerplate]
