### ISSUE TITLE
Implicit traversal through links in dictionaries

### ISSUE THREAD

**Issue by bronger** [ipld/specs#34]
I see an inconsistency in the way link within dictionaries are resolved.  I may misinterpret the spec but then one should consider clarifying it (I would be happy to file a PR in this case).

I refer to https://github.com/ipld/specs/tree/master/ipld#link-properties-convention.  The command `ipld cat --json QmCCC...CCC/cat.jpg` yields the content of `cat.jpg`.  However, I would have expected the following output:

    {
        "link": {"/": "QmCCC...222"},
        "mode": "0644",
        "owner": "jbenet"
    }

**Comment by bronger** [comment]
Is `"link"` a special key in IPLD?

**Comment by Stebalien** [comment]
You're absolutely correct, "link" is not a special key. We considered building link metadata into the spec but decided against it for simplicity; applications must decide how to store their own metadata.

Note: The `"/"` *is* a special key. That's how we encode links in JSON.

**Comment by bronger** [comment]
Thus, `ipld cat --json QmCCC...CCC/cat.jpg` is wrong and `ipld cat --json QmCCC...CCC/cat.jpg/link` is correct in order to get the binary content?

**Comment by Stebalien** [comment]
Yes.

**Comment by rvagg** [comment]
Closing due to staleness as per team agreement to clean up the issue tracker a bit (https://github.com/ipld/team-mgmt/pull/28). This doesn't mean this issue is off the table entirely, it's just not on the current active stack but may be revisited in the near future. If you feel there is something pertinent here, please speak up, reopen, or open a new issue. [/boilerplate]
