### ISSUE TITLE
Spec refining: make sure that an attribute cannot be named `.`

### ISSUE THREAD

**Issue by nicola** [ipld/specs#37]
And like in JSON Path it is escaped

**Comment by rvagg** [comment]
Closing due to staleness as per team agreement to clean up the issue tracker a bit (https://github.com/ipld/team-mgmt/pull/28). This doesn't mean this issue is off the table entirely, it's just not on the current active stack but may be revisited in the near future. If you feel there is something pertinent here, please speak up, reopen, or open a new issue. [/boilerplate]
