### ISSUE TITLE
Migrate the IANA application document to here

### ISSUE THREAD

**Issue by daviddias** [ipld/specs#40]
This was made by @mildred here: https://github.com/ipfs/specs/pull/75

@nicola can you make sure this is included in the IPLD specs repo and taken care of?

**Comment by nicola** [comment]
That is an old document that must be rewritten eventually!

**Comment by rvagg** [comment]
Closing due to staleness as per team agreement to clean up the issue tracker a bit (https://github.com/ipld/team-mgmt/pull/28). This doesn't mean this issue is off the table entirely, it's just not on the current active stack but may be revisited in the near future. If you feel there is something pertinent here, please speak up, reopen, or open a new issue. [/boilerplate]

**Comment by rvagg** [comment]
further to my boilerplate, this _is_ active and we've moved to #162 for tag 42
