### ISSUE TITLE
Prefered attribute names ..

### ISSUE THREAD

**Issue by mitra42** [ipld/specs#46]
Is there list, either as part of the IPLD spec or referenced by it, of prefered attributes. This is going to be important if metadata is to be produced by one service and consumed by another. 

Specifically ... should we use 
contenttype, content-type, mimetype, type,  for the Mime type  (presuming the value looks like that in http)

And should we use date, time, datetime for the time, and in which format (the example in https://github.com/ipld/specs/tree/master/ipld looks obviously wrong i.e. "1435398707 -0700" 
(The obvious correct format would be Zero-timezone ISO. e.g.
JS: new Date(Date.now()).toISOString() # 2017-09-18T21:43:05.038Z'
PY: datetime.utcnow().isoformat()  # 2017-09-18T14:42:02.583394

**Comment by rvagg** [comment]
Closing due to staleness as per team agreement to clean up the issue tracker a bit (https://github.com/ipld/team-mgmt/pull/28). This doesn't mean this issue is off the table entirely, it's just not on the current active stack but may be revisited in the near future. If you feel there is something pertinent here, please speak up, reopen, or open a new issue. [/boilerplate]
