### ISSUE TITLE
Structural type encoding format

### ISSUE THREAD

**Issue by Stebalien** [ipld/specs#57]
For L0, we need a format for encoding structural type definitions.

Requirements:

1. Encoded in IPLD.
2. Defined using L0 (where L0 defines a primitive type type).
3. Allows compact *value* representation (but not necessarily compact type representation).
4. Supports reflection, introspection.
5. Supports code generation.
6. Upgradable/extensible *without* consensus (i.e., no having to agree on field tags).

Good to have:

1. Generics.
2. Transformations (i.e., type definitions define transformations for upgrading/interpreting other types).
3. Pointer/value distinction: allow embedding typed objects by value instead of only by pointer.

**Comment by rvagg** [comment]
Closing due to staleness as per team agreement to clean up the issue tracker a bit (https://github.com/ipld/team-mgmt/pull/28). This doesn't mean this issue is off the table entirely, it's just not on the current active stack but may be revisited in the near future. If you feel there is something pertinent here, please speak up, reopen, or open a new issue. [/boilerplate]
