### ISSUE TITLE
IPLD.md out of date?

### ISSUE THREAD

**Issue by bjzhang** [ipld/specs#68]
Hi, this is the first time I open the issue in ipld.  Please correct me if I misunderstand something. When I try to understand the merkle dag, I am looking for relative tools. Then I start read the [IPLD.md](https://github.com/ipld/specs/blob/master/IPLD.md). I found that some examples are out of date, e.g.`ipfs object cat --fmt=yaml`. There is no cat cmd in ipfs 0.4.17. And I only find the protobuf, json and xml in "ipfs object get". Thanks in advance.

**Comment by Stebalien** [comment]
It is, unfortunately, out of date.

**Comment by bjzhang** [comment]
So, what is the corresponding command for doing something like "ipfs object cat --fmt=yaml".  I could help testing and improving the specs. It seems that "ipfs object get" will not get similar the output.

**Comment by Stebalien** [comment]
The command should be `ipfs dag get`. However, there's no `--fmt` option. `ipfs dag get` will re-format the node as JSON.

Really, you should probably use `ipfs block get` instead of `ipfs dag get`. `ipfs block get` will get a *raw* block, allowing you to decode it yourself. `ipfs dag get` is, unfortunately, a bit *lossy* due to JSON.

**Comment by vmx** [comment]
I'm closing this one as the question was answered and we now have new contents in this repository.
